/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as ClientIndexRouteImport } from './routes/_client.index'
import { Route as ClientAccountsRouteImport } from './routes/_client.accounts'
import { Route as ClientLoginRouteImport } from './routes/_client.login'
import { Route as ClientProfileRouteImport } from './routes/_client.profile'
import { Route as ClientSettingsRouteImport } from './routes/_client.settings'
import { Route as ClientStatisticsRouteImport } from './routes/_client.statistics'
import { Route as ClientTransactionsRouteImport } from './routes/_client.transactions'
import { Route as ClientTransactionsImportRouteImport } from './routes/_client.transactions-import'
import { Route as ApiPushRouteImport } from './routes/api/push'

const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAccountsRoute = ClientAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientStatisticsRoute = ClientStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTransactionsRoute = ClientTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTransactionsImportRoute =
  ClientTransactionsImportRouteImport.update({
    id: '/transactions-import',
    path: '/transactions-import',
    getParentRoute: () => ClientRoute,
  } as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ClientIndexRoute
  '/accounts': typeof ClientAccountsRoute
  '/login': typeof ClientLoginRoute
  '/profile': typeof ClientProfileRoute
  '/settings': typeof ClientSettingsRoute
  '/statistics': typeof ClientStatisticsRoute
  '/transactions': typeof ClientTransactionsRoute
  '/transactions-import': typeof ClientTransactionsImportRoute
  '/api/push': typeof ApiPushRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof ClientAccountsRoute
  '/login': typeof ClientLoginRoute
  '/profile': typeof ClientProfileRoute
  '/settings': typeof ClientSettingsRoute
  '/statistics': typeof ClientStatisticsRoute
  '/transactions': typeof ClientTransactionsRoute
  '/transactions-import': typeof ClientTransactionsImportRoute
  '/api/push': typeof ApiPushRoute
  '/': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_client': typeof ClientRouteWithChildren
  '/_client/accounts': typeof ClientAccountsRoute
  '/_client/login': typeof ClientLoginRoute
  '/_client/profile': typeof ClientProfileRoute
  '/_client/settings': typeof ClientSettingsRoute
  '/_client/statistics': typeof ClientStatisticsRoute
  '/_client/transactions': typeof ClientTransactionsRoute
  '/_client/transactions-import': typeof ClientTransactionsImportRoute
  '/api/push': typeof ApiPushRoute
  '/_client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/login'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/transactions'
    | '/transactions-import'
    | '/api/push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/login'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/transactions'
    | '/transactions-import'
    | '/api/push'
    | '/'
  id:
    | '__root__'
    | '/_client'
    | '/_client/accounts'
    | '/_client/login'
    | '/_client/profile'
    | '/_client/settings'
    | '/_client/statistics'
    | '/_client/transactions'
    | '/_client/transactions-import'
    | '/api/push'
    | '/_client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientRoute: typeof ClientRouteWithChildren
  ApiPushRoute: typeof ApiPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/accounts': {
      id: '/_client/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ClientAccountsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/login': {
      id: '/_client/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/profile': {
      id: '/_client/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/settings': {
      id: '/_client/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/statistics': {
      id: '/_client/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof ClientStatisticsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/transactions': {
      id: '/_client/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ClientTransactionsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/transactions-import': {
      id: '/_client/transactions-import'
      path: '/transactions-import'
      fullPath: '/transactions-import'
      preLoaderRoute: typeof ClientTransactionsImportRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientRouteChildren {
  ClientAccountsRoute: typeof ClientAccountsRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientStatisticsRoute: typeof ClientStatisticsRoute
  ClientTransactionsRoute: typeof ClientTransactionsRoute
  ClientTransactionsImportRoute: typeof ClientTransactionsImportRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAccountsRoute: ClientAccountsRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientStatisticsRoute: ClientStatisticsRoute,
  ClientTransactionsRoute: ClientTransactionsRoute,
  ClientTransactionsImportRoute: ClientTransactionsImportRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ClientRoute: ClientRouteWithChildren,
  ApiPushRoute: ApiPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
